### PR TITLE
108.0

### PR DESCRIPTION
**Pull request by trickypr**
# Firefox Update

## QA Requirements

- [x] Sidebar

  - [x] The sidebar exists
  - [x] The settings and addons button are visible down the bottom
  - [x] The bookmarks, history and synced tabs icons are in the sidebar
  - [x] The sidebar can be resized properly
  - [x] An [installed extension](https://addons.mozilla.org/en-US/firefox/addon/sidebar-note/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) will appear in the sidebar
  - [x] Sidebar-Tabs is Loaded and has a button visible down the bottom
  - [x] Sidebar-Tabs can add a sidebar item to the sidebar - There is **still** the race condition
  - [x] Sidebar-Tabs can remove a sidebar item to the sidebar - For some reason removing items from the sidebar is working again. Not sure why.

- [x] Extensions

  - [x] Tabliss is loading correctly
  - [x] Tabliss does not have the webextention symbol in the title bar
  - [x] uBlock origin is loading correctly
  - [x] QRCode generator is loading correctly

- [x] About dialog

  - [x] The new about dialog is present
  - [x] The dialog has not significantly changed

- [x] Pocket

  - [x] Pocket is not present in the browser

- [x] Preferences

  - [x] All tabs in preferences open
  - [x] The "More from {Vendor}" option is not present
  - [x] The sidebar preferences are present and work as expected

- [x] Welcome experience

  - [x] The import button opens the import wizard
  - [x] The theme picker is present and works as expected
  - [x] The search engine picker is present and works as expected

- [x] Pulse theme

  - [x] The tabs appear to be consistent

- [x] Mozilla theme

  - [x] The sidebar tabs are correct

- [x] Useragent
  - [x] The user agent is reporting as Mozilla Firefox

### CODE REVIEW

**Comment by trickypr** [comment]
Probably should pull this and make sure that vertical tabs etc work

**Comment by PressJump** [comment]
~~Depends on https://github.com/pulse-browser/sidebar-tabs/pull/4 as this should be fixing the race condition and also any other errors.~~

**Comment by trickypr** [comment]
This is an existing issue in alpha. You cannot block PRs on existing issues

**Comment by PressJump** [comment]
> This is an existing issue in alpha. You cannot block PRs on existing issues

A PR that was mentioned on a QA requirement which is why I linked.

**Review by PressJump — APPROVED** [review]
LGTM! 108.0🎉

**Comment by splatboydev** [comment]
🥳

**Pull request merged**
