### PR TITLE
Better welcome & setup

### LINKED ISSUE #148: Font in theme selector appears squished
theme selector w/ squished text

From IHave in Discord:
> The font's weird here
> [...]
> It feels a bit small and squashed. Could just be me/a default Firefox thing though

### LINKED ISSUE #185: Choose Tab Orientation on Setup
There has been a clear trend of an increased preference for vertical tabs in recent years. I believe that offering this option during setup will provide a more personalized and improved user experience.

### LINKED ISSUE #192: More interesting setup
It may be useful to consider incorporating design elements that make the setup page more visually appealing without detracting from its focus on productivity and minimalism. This could involve incorporating visual elements, such as icons or images, to break up text and add visual interest.

### PR DESCRIPTION
**Pull request by trickypr**

### CODE REVIEW

**Review by splatboydev — APPROVED** [review]

**Comment by PressJump** [comment]
Checking this out at the moment but was met with this on start. 
image
Not too sure if it was a build issue but rebuilding from clean to double check.

**Comment by PressJump** [comment]
I am having the same results with a clean build unfortunately. @trickypr

**Comment by trickypr** [comment]
@PressJump Rereview

**Comment by trickypr** [comment]
@PressJump Ping

**Comment by PressJump** [comment]
> @PressJump Ping

I have been summoned. Was the issue I had referenced fixed?

**Comment by trickypr** [comment]
It should be, can you re-review?

**Comment by PressJump** [comment]
> It should be, can you re-review?

Rebuilding at the moment.

**Review by PressJump — APPROVED** [review]
I believe the font is too large but otherwise it looks good to me and the issue seems to be fixed.

**Comment by trickypr** [comment]
The font size is intentional, it is a workaround for #148

**Pull request merged**
