### PR TITLE
Initial vertical tabs prototype

### LINKED ISSUE #137: Vertical tabs
This needs more thought before implementing, but here are some general ideas, but the genreal gist is that we should have something like Edge's vertical tabs. Here are my current thoughts, but design and UX work is needed:

1. It should be the option of one or the other, not both at the same time
2. Vertical tabs might be an interesting way of handling tab grouping, sort of like a merge of [Tree style tabs](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab) and [Chrome's tab grouping](https://blog.google/products/chrome/manage-tabs-with-google-chrome/)
3. It **must** feel native, unlike Tab Center Reborn + UserChrome

Technical thoughts:
- Would we be able to just move the location of the tab container? Would that be too slow because of how complex the dom is? Would that break existing functionality?

References / links:
- Tab Center Reborn is broken on pulse: #134 
- [uc.css.js's](https://github.com/aminomancer/uc.css.js) includes an implementation, which might have some interesting ideas for structure, but we do not want to rip them off.

## TODO
- [x] Basic implementation (#167)
- [ ] Clean up the pulse theme
- [x] Add the option to compress the tabs down to just the favicon when not hovered
- [ ] Profit?

### PR DESCRIPTION
**Pull request by trickypr**
This provides an vertical tab implementation so we can get some user feedback from people in discord.

### CODE REVIEW

**Comment by trickypr** [comment]
Should not close the issue

**Comment by PressJump** [comment]
Hey, this looks very nice but it does take a large amount of space on screen including if the user wanted to utilize the sidebar. It would be great if the user was able to resize the vertical tabs page to their liking dependent on the content they are looking at.   
image
What are your thoughts?

**Comment by trickypr** [comment]
See #137 

> - [ ] Clean up the pulse theme
> - [ ] Add the option to compress the tabs down to just the favicon when not hovered

The point of this is to get a basic implementation. I will do better styling, experiment with docking the sidebars to the right etc. in another PR.

**Comment by PressJump** [comment]
> See #137
> 
> > * [ ]  Clean up the pulse theme
> > * [ ]  Add the option to compress the tabs down to just the favicon when not hovered
> 
> The point of this is to get a basic implementation. I will do better styling, experiment with docking the sidebars to the right etc. in another PR.

Fair.

**Review by PressJump — APPROVED** [review]
LGTM! Vertical tabs community will like this one.

**Pull request merged**
