### PR TITLE
Upgrade Firefox to 106.0.5

### LINKED ISSUE #113: ❗ Pulse has out of date dependencies
## Outdated Dependencies
- firefox: 106.0.5 → 107.0
- ublock: 1.44.4 → 1.45.2

You can opt in or out of these requests by creating a pull request to the [update bot repository](https://github.com/pulse-browser/update-bot/blob/main/repos.json)

### PR DESCRIPTION
**Pull request by PressJump**
Upgrade Firefox to 106.0.5, fixing bad patches and removing Firefox-view button on the top left.

Fixes #113

### CODE REVIEW

**Review by splatboydev — APPROVED** [review]
I think trigure might be a misspelling but it looks fine other than that.

```js
+  /**
+   * Displays the welcome dialog. Trigured `_maybeShowDefaultBrowserPrompt`.
+   *
+   * @todo Add gluon docs for how to show custom popups on startup
+   * @patch Pulse Browser
+   */
```

**Comment by trickypr** [comment]
Will review this on Friday afternoon or Saturday

**Comment by PressJump** [comment]
## QA Requirements

- [x] Sidebar

  - [x] The sidebar exists
  - [x] The settings and addons button are visible down the bottom
  - [x] The bookmarks, history and synced tabs icons are in the sidebar
  - [x] The sidebar can be resized properly
  - [x] An [installed extension](https://addons.mozilla.org/en-US/firefox/addon/sidebar-note/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) will appear in the sidebar
  - [x] Sidebar-Tabs is Loaded and has a button visible down the bottom
  - [x] Sidebar-Tabs can add a sidebar item to the sidebar
  - [x] Sidebar-Tabs can remove a sidebar item to the sidebar



- [x] Extensions

  - [x] Tabliss is loading correctly
  - [x] Tabliss does not have the webextention symbol in the title bar
  - [x] uBlock origin is loading correctly
  - [x] QR-Generator is loading correctly

- [x] About dialog

  - [x] The new about dialog is present
  - [x] The dialog has not significantly changed

- [x] Pocket

  - [x] Pocket is not present in the browser

- [x] Preferences

  - [x] All tabs in preferences open
  - [x] The "More from {Vendor}" option is not present
  - [x] The sidebar preferences are present and work as expected

- [x] Welcome experience

  - [x] The import button opens the import wizard
  - [x] The theme picker is present and works as expected
  - [ ] The search engine picker is present and works as expected

- [x] Pulse theme

  - [x] The tabs appear to be consistent

- [x] Mozilla theme

  - [x] The sidebar tabs are correct

- [x] Useragent
  - [x] The user agent is reporting as Mozilla Firefox

**Comment by PressJump** [comment]
Search engine picker does not work as expected from the welcome experience but other QA checks pass.

**Review by trickypr — CHANGES_REQUESTED** [review]
You need to fix QA bugs before merging

**Review by trickypr — APPROVED** [review]

**Pull request merged**
