### PR TITLE
Extended sidebar functionallity

### PR DESCRIPTION
**Pull request by trickypr**
This is a work in progress pr that will provide:
- A more powerful sidebar api
- Assorted bug fixes
- The ability to add websites to the sidebar

Note: This is currently blocking feature freeze and beta builds

### CODE REVIEW

**Comment by PressJump** [comment]
Things to do:

- [ ] Fix Resizing
- [x] Api Expansion
- [x] Fix Conflict issues with new firefox version
- [ ] Fix extension errors

This list will be extended as development resumes in the upcoming days. ETC Friday

**Comment by PressJump** [comment]
# Major Addition (Sidebar)

## QA Requirements

- [x] Sidebar

  - [x] The sidebar exists
  - [x] The settings and addons button are visible down the bottom
  - [x] The bookmarks, history and synced tabs icons are in the sidebar
  - [x] An [installed extension](https://addons.mozilla.org/en-US/firefox/addon/sidebar-note/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) will appear in the sidebar

- [x] Extensions

  - [x] Tabliss is loading correctly
  - [x] Tabliss does not have the webextention symbol in the title bar
  - [x] uBlock origin is loading correctly
  - [x] FirePicker is loading correctly

- [x] About dialog

  - [x] The new about dialog is present
  - [x] The dialog has not significantly changed

- [x] Pocket

  - [x] Pocket is not present in the browser

- [x] Preferences

  - [x] All tabs in preferences open
  - [x] The "More from {Vendor}" option is not present
  - [x] The sidebar preferences are present and work as expected

- [x] Welcome experience

  - [x] The import button opens the import wizard
  - [x] The theme picker is present and works as expected
  - [x] The search engine picker is present and works as expected

- [x] Pulse theme

  - [x] The tabs appear to be consistent

- [x] Mozilla theme

  - [x] The sidebar tabs are correct

- [x] Useragent
  - [x] The user agent is reporting as Mozilla Firefox

**Comment by PressJump** [comment]
@trickypr Extended sidebar functionallity #100 complete and ready for review.

**Review by trickypr — COMMENTED** [review]
With the changes made, it should be all good, but you will need to review it before merging

**Review by PressJump — APPROVED** [review]
Extended sidebar functionality, Feature Freeze!

**Pull request merged**
