### PR TITLE
107.0.1

### LINKED ISSUE #156: ❗ Pulse has out of date dependencies
## Outdated Dependencies
- firefox: 108.0.1 → 109.0
- ublock: 1.45.2 → uBOLite_0.1.22.12266
- sidebar-tabs: v0.4.0 → v0.5.0

You can opt in or out of these requests by creating a pull request to the [update bot repository](https://github.com/pulse-browser/update-bot/blob/main/repos.json)

### PR DESCRIPTION
**Pull request by trickypr**
# Firefox Update

This bumps Firefox up to `107.0.1` for security and performance reasons. Reviewers check the following before continuing:

## QA Requirements

- [ ] Sidebar

  - [x] The sidebar exists
  - [x] The settings and addons button are visible down the bottom
  - [x] The bookmarks, history and synced tabs icons are in the sidebar
  - [x] The sidebar can be resized properly
  - [x] An [installed extension](https://addons.mozilla.org/en-US/firefox/addon/sidebar-note/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) will appear in the sidebar
  - [x] Sidebar-Tabs is Loaded and has a button visible down the bottom
  - [ ] Sidebar-Tabs can add a sidebar item to the sidebar - There is still the race condition reported in pulse-browser/sidebartabs#2
  - [ ] Sidebar-Tabs can remove a sidebar item to the sidebar  - An error [here](https://github.com/pulse-browser/sidebar-tabs/blob/eecd2991e8eb87ee1942c3e3f52054d4021f27d7/js/background.js#L19) causes the addon to crash

Note: Neither sidebar issue are related to the update.

- [x] Extensions

  - [x] Tabliss is loading correctly
  - [x] Tabliss does not have the webextention symbol in the title bar
  - [x] uBlock origin is loading correctly
  - [x] QRCode generator is loading correctly

- [x] About dialog

  - [x] The new about dialog is present
  - [x] The dialog has not significantly changed

- [x] Pocket

  - [x] Pocket is not present in the browser

- [x] Preferences

  - [x] All tabs in preferences open
  - [x] The "More from {Vendor}" option is not present
  - [x] The sidebar preferences are present and work as expected

- [x] Welcome experience

  - [x] The import button opens the import wizard
  - [x] The theme picker is present and works as expected
  - [x] The search engine picker is present and works as expected

- [x] Pulse theme

  - [x] The tabs appear to be consistent

- [x] Mozilla theme

  - [x] The sidebar tabs are correct

- [x] Useragent
  - [x] The user agent is reporting as Mozilla Firefox

Depends on  #170
Fixes #156

### CODE REVIEW

**Comment by PressJump** [comment]
Hmm, interesting that the sidebar issues are related to extension. Thats a new one.

**Comment by trickypr** [comment]
The relevant error has been popping up regularly for ages, so it is nothing new

**Comment by PressJump** [comment]
> The relevant error has been popping up regularly for ages, so it is nothing new

There is an error but this does not block the functionality of the sidebar so QA for sidebar should be all good. This issue was fixed on https://github.com/pulse-browser/sidebar-tabs/pull/4 so that error will stop showing up in console when merged.

**Comment by PressJump** [comment]
Depends on https://github.com/pulse-browser/sidebar-tabs/pull/4

**Comment by trickypr** [comment]
Replaced by #175

**Pull request closed without merging**
